openapi: 3.0.1
info:
  title: Transaction API
  version: 1.0.0
  contact:
    email: kleyvissonmatias@gmail.com
servers:
  - url: http://localhost:8080/api/v1/transactions
tags:
  - name: Transactions
    description: transactions
paths:
  /authorize:
    post:
      tags:
        - Transactions
      summary: Creates a new transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  description: Account number
                totalAmount:
                  type: number
                  format: double
                  description: Total transaction amount
                mcc:
                  type: string
                  description: MCC (Merchant Category Code)
                merchant:
                  type: string
                  description: Merchant name
      responses:
        '200':
          description: Transaction response
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: Transaction status code